/*
 * FAñadirPasajero.java
 *
 * Created on December 14, 2006, 10:04 PM
 */

package gui;

import aeropuerto.*;

/**
 *
 * @author  jalbert
 */
public class FAviónPasajeros extends javax.swing.JDialog implements java.awt.event.ActionListener, java.awt.event.WindowListener {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form FAñadirPasajero */
    public FAviónPasajeros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private ControladorAereo torre;
    
    public FAviónPasajeros(ControladorAereo torre) {
        this(null, true);
        this.torre = torre;
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tCantCombust = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tConsumo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tCantPasajeros = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tDistanciaRecorrida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tAerolinea = new javax.swing.JComboBox();
        
        setTitle("A\u00f1ada avi\u00f3n de pasajeros");
        setModal(true);
        addWindowListener(this);
        
        okButton.setText("OK");
        okButton.addActionListener(this);
        
        
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this);
        
        
        jLabel1.setText("Matr\u00edcula");
        
        tMatricula.setText("1");
        tMatricula.setName("");
        
        jLabel2.setText("Cantidad de combustible");
        
        tCantCombust.setText("0");
        
        jLabel3.setText("Consumo cada 30 minutos");
        
        tConsumo.setText("0");
        
        jLabel4.setText("Cantidad de pasajeros");
        
        tCantPasajeros.setText("0");
        
        jLabel5.setText("Distancia recorrida");
        
        tDistanciaRecorrida.setText("0");
        
        jLabel6.setText("Aerol\u00ednea");
        
        tAerolinea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "British Air Ways", "Aeroflot", "Cubana", "Iberia", "Air France", "Aero Caribean", "Aero Gaviota" }));
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(tConsumo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .add(tMatricula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(tAerolinea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .add(tCantPasajeros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(35, 35, 35)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabel2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                .add(org.jdesktop.layout.GroupLayout.LEADING, tDistanciaRecorrida)
                .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .add(tCantCombust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36))
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(97, 97, 97)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(107, 107, 107))
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1)
                .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(tMatricula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(tAerolinea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tCantCombust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel3)
                .add(jLabel4)
                .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tConsumo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createSequentialGroup()
                .add(46, 46, 46)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(tCantPasajeros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(tDistanciaRecorrida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(62, 62, 62)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(cancelButton)
                .add(okButton))
                .addContainerGap(40, Short.MAX_VALUE))
                );
        pack();
    }
    
// Code for dispatching events from components to event handlers.
    
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == okButton) {
            FAviónPasajeros.this.okButtonActionPerformed(evt);
        } else if (evt.getSource() == cancelButton) {
            FAviónPasajeros.this.cancelButtonActionPerformed(evt);
        }
    }
    
    public void windowActivated(java.awt.event.WindowEvent evt) {
    }
    
    public void windowClosed(java.awt.event.WindowEvent evt) {
    }
    
    public void windowClosing(java.awt.event.WindowEvent evt) {
        if (evt.getSource() == FAviónPasajeros.this) {
            FAviónPasajeros.this.closeDialog(evt);
        }
    }
    
    public void windowDeactivated(java.awt.event.WindowEvent evt) {
    }
    
    public void windowDeiconified(java.awt.event.WindowEvent evt) {
    }
    
    public void windowIconified(java.awt.event.WindowEvent evt) {
    }
    
    public void windowOpened(java.awt.event.WindowEvent evt) {
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        torre.Adicionar(
                new AviónPasajeros(
                    tMatricula.getText(),
                    tAerolinea.getSelectedItem().toString(),
                    Double.parseDouble(tCantCombust.getText()),
                    Double.parseDouble(tConsumo.getText()),
                    Integer.parseInt(tCantPasajeros.getText()),
                    Double.parseDouble(tDistanciaRecorrida.getText())
                )
             );
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox tAerolinea;
    private javax.swing.JTextField tCantCombust;
    private javax.swing.JTextField tCantPasajeros;
    private javax.swing.JTextField tConsumo;
    private javax.swing.JTextField tDistanciaRecorrida;
    private javax.swing.JTextField tMatricula;
// End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
