/*
 * FAviónCarga.java
 *
 * Created on December 14, 2006, 10:40 PM
 */

package gui;

import aeropuerto.*;

/**
 *
 * @author  jalbert
 */
public class FJetEjecutivo extends javax.swing.JDialog implements java.awt.event.ActionListener, java.awt.event.WindowListener {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form FAviónCarga */
    public FJetEjecutivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     private ControladorAereo torre;
    
    public FJetEjecutivo(ControladorAereo torre) {
        this(null, true);
        this.torre = torre;
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tMatricula = new javax.swing.JTextField();
        tAerolinea = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tCantCombust = new javax.swing.JTextField();
        tConsumo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tNivelUrgencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        
        setTitle("A\u00f1ada jets ejecutivos");
        setModal(true);
        addWindowListener(this);
        
        okButton.setText("OK");
        okButton.addActionListener(this);
        
        
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this);
        
        
        jLabel1.setText("Matr\u00edcula");
        
        tMatricula.setText("1");
        tMatricula.setName("");
        
        tAerolinea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "British Air Ways", "Aeroflot", "Cubana", "Iberia", "Air France", "Aero Caribean", "Aero Gaviota" }));
        
        jLabel6.setText("Aerol\u00ednea");
        
        jLabel2.setText("Cantidad de combustible");
        
        tCantCombust.setText("0");
        
        tConsumo.setText("0");
        
        jLabel3.setText("Consumo cada 30 mins");
        
        tNivelUrgencia.setText("1");
        tNivelUrgencia.setName("");
        
        jLabel4.setText("Nivel de urgencia");
        
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .add(tMatricula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(tConsumo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(tAerolinea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(37, 37, 37)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(tCantCombust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel2)))
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(tNivelUrgencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4))
                .add(layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(okButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(52, 52, 52)
                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tMatricula, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tConsumo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                .add(61, 61, 61)
                .add(jLabel4))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                .add(layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tCantCombust, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createSequentialGroup()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tAerolinea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tNivelUrgencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(50, 50, 50)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(okButton)
                .add(cancelButton))
                .addContainerGap(36, Short.MAX_VALUE))
                );
        pack();
    }
    
// Code for dispatching events from components to event handlers.
    
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == okButton) {
            FJetEjecutivo.this.okButtonActionPerformed(evt);
        } else if (evt.getSource() == cancelButton) {
            FJetEjecutivo.this.cancelButtonActionPerformed(evt);
        }
    }
    
    public void windowActivated(java.awt.event.WindowEvent evt) {
    }
    
    public void windowClosed(java.awt.event.WindowEvent evt) {
    }
    
    public void windowClosing(java.awt.event.WindowEvent evt) {
        if (evt.getSource() == FJetEjecutivo.this) {
            FJetEjecutivo.this.closeDialog(evt);
        }
    }
    
    public void windowDeactivated(java.awt.event.WindowEvent evt) {
    }
    
    public void windowDeiconified(java.awt.event.WindowEvent evt) {
    }
    
    public void windowIconified(java.awt.event.WindowEvent evt) {
    }
    
    public void windowOpened(java.awt.event.WindowEvent evt) {
    }// </editor-fold>//GEN-END:initComponents
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        torre.Adicionar(
                new JetEjecutivo(
                    tMatricula.getText(),
                    tAerolinea.getSelectedItem().toString(),
                    Double.parseDouble(tCantCombust.getText()),
                    Double.parseDouble(tConsumo.getText()),
                    Integer.parseInt(tNivelUrgencia.getText())
                )
             );
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
        
// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox tAerolinea;
    private javax.swing.JTextField tCantCombust;
    private javax.swing.JTextField tConsumo;
    private javax.swing.JTextField tMatricula;
    private javax.swing.JTextField tNivelUrgencia;
// End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
